datasets:
  declarations:
    type: file
    path: "test_docetl.json"

default_model: gemini/gemini-2.0-flash

system_prompt:
  dataset_description: A collection of disaster declaration requests submitted to FEMA.

operations:
  - name: parse_page_one
    type: map
    pdf_url_key: "page_1"
    prompt: |
      Extract information from the attached page of a completed
      form submitted to FEMA.

      Format all dates as "YYYY-MM-DD".
    output:
      schema:
        request_date: string
        state_or_tribe: string
        request_purpose: enum[Major Disaster, Emergency]
        incident_start_date: string
        incident_end_date: string
        incident_type: "list[enum[
          Drought, Earthquake, Explosion, Fire, Severe Storm, Flood, Hurricane,
          Landslide, Mudslide, Snowstorm, Straight-Line Winds, Tidal Wave,
          Tornado, Tropical Depression, Tropical Storm, Tsunami, Volcanic Eruption,
          Winter Storm, Other]
          ]"
        incident_type_other: string
        damage_description: string
        resource_description: string
pipeline:
  steps:
    - name: parse_declarations
      input: declarations
      operations:
        - parse_page_one
  output:
    type: file
    path: "results.json"
    intermediate_dir: "intermediate_results"
